version: "3.1"
services:
  web:
    image: clam-api/api
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - clam-api

  clamd:
    image: clam-api/clamd
    networks:
      - clam-api

networks:
  clam-api:
